// frontend/src/pages/StatistiquesPage.tsx
import { useState, useEffect } from 'react';
import statistiqueService from '../services/statistique.service';
import anneeExerciceService from '../services/annee-exercice.service';
import classeService from '../services/classe.service';
import type { 
  StatistiqueEnfant,
  StatistiqueStaff,
  StatistiqueFilterRequest,
  AnneeExercice,
  Classe
} from '../types';
import './StatistiquesPage.css';

export function StatistiquesPage() {
  const [activeTab, setActiveTab] = useState<'enfants' | 'staffs'>('enfants');
  const [statistiquesEnfants, setStatistiquesEnfants] = useState<StatistiqueEnfant[]>([]);
  const [statistiquesStaffs, setStatistiquesStaffs] = useState<StatistiqueStaff[]>([]);
  const [annees, setAnnees] = useState<AnneeExercice[]>([]);
  const [classes, setClasses] = useState<Classe[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showFilters, setShowFilters] = useState(true);
  
  const [filters, setFilters] = useState<StatistiqueFilterRequest>({
    anneeExerciceId: undefined,
    classeId: undefined,
    genre: undefined,
  });

  useEffect(() => {
    loadAnnees();
    loadClasses();
  }, []);

  useEffect(() => {
    if (activeTab === 'enfants') {
      loadStatistiquesEnfants();
    } else {
      loadStatistiquesStaffs();
    }
  }, [activeTab, filters]);

  const loadAnnees = async () => {
    try {
      const data = await anneeExerciceService.getAllAnneesExercice();
      setAnnees(data);
    } catch (err: any) {
      console.error('Erreur lors du chargement des années', err);
    }
  };

  const loadClasses = async () => {
    try {
      const data = await classeService.getAllClasses();
      setClasses(data);
    } catch (err: any) {
      console.error('Erreur lors du chargement des classes', err);
    }
  };

  const loadStatistiquesEnfants = async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await statistiqueService.getStatistiquesEnfants(filters);
      setStatistiquesEnfants(data);
    } catch (err: any) {
      setError(err.message || 'Erreur lors du chargement des statistiques');
    } finally {
      setLoading(false);
    }
  };

  const loadStatistiquesStaffs = async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await statistiqueService.getStatistiquesStaffs(filters);
      setStatistiquesStaffs(data);
    } catch (err: any) {
      setError(err.message || 'Erreur lors du chargement des statistiques');
    } finally {
      setLoading(false);
    }
  };

  const handleFilterChange = (field: keyof StatistiqueFilterRequest, value: any) => {
    setFilters(prev => ({
      ...prev,
      [field]: value || undefined
    }));
  };

  const handleResetFilters = () => {
    setFilters({
      anneeExerciceId: undefined,
      classeId: undefined,
      genre: undefined,
    });
  };

  const formatPourcentage = (pourcentage: number) => {
    return `${pourcentage.toFixed(2)}%`;
  };

  const formatAnnee = (annee: string) => {
    // Extrait l'année de début (ex: "2023-2024" => "2023")
    return annee.split('-')[0];
  };

  const getRangBadgeColor = (rang: number) => {
    if (rang === 1) return 'badge-gold';
    if (rang === 2) return 'badge-silver';
    if (rang === 3) return 'badge-bronze';
    return 'badge-default';
  };

  return (
    <div className="statistiques-page">
      <div className="page-header">
        <h1>📊 Statistiques</h1>
        <p>Statistiques de participation et de progression des enfants et des staffs</p>
      </div>

      {error && (
        <div className="alert alert-danger">
          {error}
        </div>
      )}

      {/* Onglets */}
      <div className="tabs">
        <button 
          className={`tab ${activeTab === 'enfants' ? 'active' : ''}`}
          onClick={() => setActiveTab('enfants')}
        >
          👦 Enfants
        </button>
        <button 
          className={`tab ${activeTab === 'staffs' ? 'active' : ''}`}
          onClick={() => setActiveTab('staffs')}
        >
          👨‍🏫 Staffs
        </button>
      </div>

      {/* Filtres */}
      <div className="filters-section">
        <button 
          className="btn btn-secondary btn-sm"
          onClick={() => setShowFilters(!showFilters)}
        >
          {showFilters ? '📉 Masquer les filtres' : '📊 Afficher les filtres'}
        </button>

        {showFilters && (
          <div className="filters-card">
            <h3>🔍 Filtres</h3>
            <div className="filters-grid">
              <div className="form-group">
                <label>Année d'exercice</label>
                <select
                  value={filters.anneeExerciceId || ''}
                  onChange={(e) => handleFilterChange('anneeExerciceId', e.target.value ? Number(e.target.value) : undefined)}
                  className="form-control"
                >
                  <option value="">Toutes les années</option>
                  {annees.map(annee => (
                    <option key={annee.id} value={annee.id}>{formatAnnee(annee.annee)}</option>
                  ))}
                </select>
              </div>

              {activeTab === 'enfants' && (
                <>
                  <div className="form-group">
                    <label>Classe</label>
                    <select
                      value={filters.classeId || ''}
                      onChange={(e) => handleFilterChange('classeId', e.target.value ? Number(e.target.value) : undefined)}
                      className="form-control"
                    >
                      <option value="">Toutes les classes</option>
                      {classes.map(classe => (
                        <option key={classe.id} value={classe.id}>{classe.nom}</option>
                      ))}
                    </select>
                  </div>

                  <div className="form-group">
                    <label>Genre</label>
                    <select
                      value={filters.genre || ''}
                      onChange={(e) => handleFilterChange('genre', e.target.value || undefined)}
                      className="form-control"
                    >
                      <option value="">Tous</option>
                      <option value="M">Masculin</option>
                      <option value="F">Féminin</option>
                    </select>
                  </div>
                </>
              )}
            </div>

            <div className="filters-actions">
              <button 
                className="btn btn-secondary btn-sm"
                onClick={handleResetFilters}
              >
                🔄 Réinitialiser
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Résultats */}
      <div className="results-section">
        {loading ? (
          <div className="loading">Chargement des statistiques...</div>
        ) : activeTab === 'enfants' ? (
          <div className="statistiques-enfants">
            <h2>📊 Statistiques des Enfants ({statistiquesEnfants.length})</h2>
            
            {statistiquesEnfants.length === 0 ? (
              <div className="empty-state">
                Aucune statistique disponible pour les critères sélectionnés.
              </div>
            ) : (
              <div className="table-responsive">
                <table className="table statistiques-table">
                  <thead>
                    <tr>
                      <th>Nom & Prénom</th>
                      <th>Classe</th>
                      <th>Année</th>
                      <th>Programmes Complétés</th>
                      <th>Participation Activités</th>
                      <th>Rang</th>
                      <th>Présence CP</th>
                      <th>Rang</th>
                    </tr>
                  </thead>
                  <tbody>
                    {statistiquesEnfants.map((stat) => (
                      <tr key={stat.enfantId}>
                        <td>
                          <strong>{stat.nom} {stat.prenom}</strong>
                        </td>
                        <td>{stat.classe}</td>
                        <td>{formatAnnee(stat.anneeExercice)}</td>
                        <td>
                          <div className="stat-cell">
                            <div className="stat-value">
                              {formatPourcentage(stat.pourcentageProgrammes)}
                            </div>
                            <div className="stat-detail">
                              {stat.nombreProgrammesCompletes}/{stat.totalProgrammesClasse}
                            </div>
                          </div>
                        </td>
                        <td>
                          <div className="stat-cell">
                            <div className="stat-value">
                              {formatPourcentage(stat.pourcentageActivites)}
                            </div>
                            <div className="stat-detail">
                              {stat.nombreParticipationsActivites}/{stat.totalActivites}
                            </div>
                          </div>
                        </td>
                        <td>
                          <span className={`badge ${getRangBadgeColor(stat.rangActivites)}`}>
                            #{stat.rangActivites}
                          </span>
                        </td>
                        <td>
                          <div className="stat-cell">
                            <div className="stat-value">
                              {formatPourcentage(stat.pourcentageCP)}
                            </div>
                            <div className="stat-detail">
                              {stat.nombrePresencesCP}/{stat.totalCP}
                            </div>
                          </div>
                        </td>
                        <td>
                          <span className={`badge ${getRangBadgeColor(stat.rangCP)}`}>
                            #{stat.rangCP}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        ) : (
          <div className="statistiques-staffs">
            <h2>📊 Statistiques des Staffs ({statistiquesStaffs.length})</h2>
            
            {statistiquesStaffs.length === 0 ? (
              <div className="empty-state">
                Aucune statistique disponible pour les critères sélectionnés.
              </div>
            ) : (
              <div className="table-responsive">
                <table className="table statistiques-table">
                  <thead>
                    <tr>
                      <th>Nom & Prénom</th>
                      <th>Rôle</th>
                      <th>Année</th>
                      <th>Participation Activités</th>
                      <th>Rang</th>
                      <th>Présence CP</th>
                      <th>Rang</th>
                    </tr>
                  </thead>
                  <tbody>
                    {statistiquesStaffs.map((stat) => (
                      <tr key={stat.staffId}>
                        <td>
                          <strong>{stat.nom} {stat.prenom}</strong>
                        </td>
                        <td>{stat.role}</td>
                        <td>{formatAnnee(stat.anneeExercice)}</td>
                        <td>
                          <div className="stat-cell">
                            <div className="stat-value">
                              {formatPourcentage(stat.pourcentageActivites)}
                            </div>
                            <div className="stat-detail">
                              {stat.nombreParticipationsActivites}/{stat.totalActivites}
                            </div>
                          </div>
                        </td>
                        <td>
                          <span className={`badge ${getRangBadgeColor(stat.rangActivites)}`}>
                            #{stat.rangActivites}
                          </span>
                        </td>
                        <td>
                          <div className="stat-cell">
                            <div className="stat-value">
                              {formatPourcentage(stat.pourcentageCP)}
                            </div>
                            <div className="stat-detail">
                              {stat.nombrePresencesCP}/{stat.totalCP}
                            </div>
                          </div>
                        </td>
                        <td>
                          <span className={`badge ${getRangBadgeColor(stat.rangCP)}`}>
                            #{stat.rangCP}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// mobile/src/views/StatistiquesPage.vue
<template>
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
          <img src="/assets/logo.png" alt="Logo" class="header-logo" />
        </ion-buttons>
        <ion-title>Statistiques</ion-title>
        <ion-buttons slot="end">
          <ion-button @click="loadData" :disabled="loading">
            <ion-icon :icon="syncOutline"></ion-icon>
          </ion-button>
        </ion-buttons>
      </ion-toolbar>
      
      <!-- Segment pour switcher entre Enfants et Staffs -->
      <ion-toolbar>
        <ion-segment :value="activeTab" @ionChange="onTabChange($event)">
          <ion-segment-button value="enfants">
            <ion-label>Enfants</ion-label>
          </ion-segment-button>
          <ion-segment-button value="staffs">
            <ion-label>Staffs</ion-label>
          </ion-segment-button>
        </ion-segment>
      </ion-toolbar>
    </ion-header>

    <ion-content :fullscreen="true">
      <!-- Messages d'erreur et succès -->
      <ion-toast
        :is-open="!!error"
        :message="error || ''"
        :duration="3000"
        position="top"
        color="danger"
        @didDismiss="error = null"
      ></ion-toast>

      <!-- Loading -->
      <div v-if="loading" class="ion-text-center ion-padding">
        <ion-spinner></ion-spinner>
        <p>Chargement...</p>
      </div>

      <!-- Tab Enfants -->
      <div v-else-if="activeTab === 'enfants'">
        <!-- Filtres -->
        <ion-card>
          <ion-card-header>
            <div style="display: flex; justify-content: space-between; align-items: center;">
              <ion-card-title>Filtres</ion-card-title>
              <ion-button fill="clear" @click="showFilters = !showFilters">
                <ion-icon :icon="chevronBackOutline" :class="{ 'rotate-up': showFilters, 'rotate-down': !showFilters }"></ion-icon>
              </ion-button>
            </div>
          </ion-card-header>
          <ion-card-content v-if="showFilters">
            <ion-item>
              <ion-label>Année d'exercice</ion-label>
              <ion-select v-model="filterAnneeId" placeholder="Toutes">
                <ion-select-option :value="null">Toutes</ion-select-option>
                <ion-select-option v-for="annee in anneesExercice" :key="annee.id" :value="annee.id">
                  {{ formatAnnee(annee.annee) }}
                </ion-select-option>
              </ion-select>
            </ion-item>
            
            <ion-item>
              <ion-label>Classe</ion-label>
              <ion-select v-model="filterClasseId" placeholder="Toutes">
                <ion-select-option :value="null">Toutes</ion-select-option>
                <ion-select-option v-for="classe in classes" :key="classe.id" :value="classe.id">
                  {{ classe.nom }}
                </ion-select-option>
              </ion-select>
            </ion-item>
            
            <ion-item>
              <ion-label>Genre</ion-label>
              <ion-select v-model="filterGenre" placeholder="Tous">
                <ion-select-option :value="null">Tous</ion-select-option>
                <ion-select-option value="GARCON">Garçon</ion-select-option>
                <ion-select-option value="FILLE">Fille</ion-select-option>
              </ion-select>
            </ion-item>
            
            <ion-button expand="block" fill="clear" @click="resetFilters">
              Réinitialiser les filtres
            </ion-button>
          </ion-card-content>
        </ion-card>

        <!-- Liste des statistiques enfants -->
        <ion-card v-if="statistiquesEnfants.length === 0 && !loading">
          <ion-card-content class="ion-text-center">
            Aucune statistique disponible
          </ion-card-content>
        </ion-card>

        <ion-card v-for="stat in statistiquesEnfants" :key="stat.enfantId">
          <ion-card-header>
            <ion-card-title>{{ stat.nom }} {{ stat.prenom }}</ion-card-title>
            <ion-card-subtitle>{{ stat.classe }} - {{ formatAnnee(stat.anneeExercice) }}</ion-card-subtitle>
          </ion-card-header>
          <ion-card-content>
            <!-- Programmes complétés -->
            <div class="stat-row">
              <ion-label>
                <h3>Programmes Complétés</h3>
                <p>{{ stat.nombreProgrammesCompletes }} / {{ stat.totalProgrammesClasse }}</p>
              </ion-label>
              <div class="stat-value">
                <ion-badge color="primary">{{ formatPourcentage(stat.pourcentageProgrammes) }}</ion-badge>
              </div>
            </div>
            
            <!-- Participation Activités -->
            <div class="stat-row">
              <ion-label>
                <h3>Participation Activités</h3>
                <p>{{ stat.nombreParticipationsActivites }} / {{ stat.totalActivites }}</p>
              </ion-label>
              <div class="stat-value">
                <ion-badge :color="getRangBadgeColor(stat.rangActivites)">
                  {{ formatPourcentage(stat.pourcentageActivites) }}
                </ion-badge>
                <ion-chip :color="getRangBadgeColor(stat.rangActivites)">
                  Rang #{{ stat.rangActivites }}
                </ion-chip>
              </div>
            </div>
            
            <!-- Présence CP -->
            <div class="stat-row">
              <ion-label>
                <h3>Présence CP</h3>
                <p>{{ stat.nombrePresencesCP }} / {{ stat.totalCP }}</p>
              </ion-label>
              <div class="stat-value">
                <ion-badge :color="getRangBadgeColor(stat.rangCP)">
                  {{ formatPourcentage(stat.pourcentageCP) }}
                </ion-badge>
                <ion-chip :color="getRangBadgeColor(stat.rangCP)">
                  Rang #{{ stat.rangCP }}
                </ion-chip>
              </div>
            </div>
          </ion-card-content>
        </ion-card>
      </div>

      <!-- Tab Staffs -->
      <div v-else-if="activeTab === 'staffs'">
        <!-- Filtres -->
        <ion-card>
          <ion-card-header>
            <div style="display: flex; justify-content: space-between; align-items: center;">
              <ion-card-title>Filtres</ion-card-title>
              <ion-button fill="clear" @click="showFiltersStaff = !showFiltersStaff">
                <ion-icon :icon="chevronBackOutline" :class="{ 'rotate-up': showFiltersStaff, 'rotate-down': !showFiltersStaff }"></ion-icon>
              </ion-button>
            </div>
          </ion-card-header>
          <ion-card-content v-if="showFiltersStaff">
            <ion-item>
              <ion-label>Année d'exercice</ion-label>
              <ion-select v-model="filterStaffAnneeId" placeholder="Toutes">
                <ion-select-option :value="null">Toutes</ion-select-option>
                <ion-select-option v-for="annee in anneesExercice" :key="annee.id" :value="annee.id">
                  {{ formatAnnee(annee.annee) }}
                </ion-select-option>
              </ion-select>
            </ion-item>
            
            <ion-button expand="block" fill="clear" @click="resetStaffFilters">
              Réinitialiser les filtres
            </ion-button>
          </ion-card-content>
        </ion-card>

        <!-- Liste des statistiques staffs -->
        <ion-card v-if="statistiquesStaffs.length === 0 && !loading">
          <ion-card-content class="ion-text-center">
            Aucune statistique disponible
          </ion-card-content>
        </ion-card>

        <ion-card v-for="stat in statistiquesStaffs" :key="stat.staffId">
          <ion-card-header>
            <ion-card-title>{{ stat.nom }} {{ stat.prenom }}</ion-card-title>
            <ion-card-subtitle>{{ stat.role }} - {{ formatAnnee(stat.anneeExercice) }}</ion-card-subtitle>
          </ion-card-header>
          <ion-card-content>
            <!-- Participation Activités -->
            <div class="stat-row">
              <ion-label>
                <h3>Participation Activités</h3>
                <p>{{ stat.nombreParticipationsActivites }} / {{ stat.totalActivites }}</p>
              </ion-label>
              <div class="stat-value">
                <ion-badge :color="getRangBadgeColor(stat.rangActivites)">
                  {{ formatPourcentage(stat.pourcentageActivites) }}
                </ion-badge>
                <ion-chip :color="getRangBadgeColor(stat.rangActivites)">
                  Rang #{{ stat.rangActivites }}
                </ion-chip>
              </div>
            </div>
            
            <!-- Présence CP -->
            <div class="stat-row">
              <ion-label>
                <h3>Présence CP</h3>
                <p>{{ stat.nombrePresencesCP }} / {{ stat.totalCP }}</p>
              </ion-label>
              <div class="stat-value">
                <ion-badge :color="getRangBadgeColor(stat.rangCP)">
                  {{ formatPourcentage(stat.pourcentageCP) }}
                </ion-badge>
                <ion-chip :color="getRangBadgeColor(stat.rangCP)">
                  Rang #{{ stat.rangCP }}
                </ion-chip>
              </div>
            </div>
          </ion-card-content>
        </ion-card>
      </div>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonButtons,
  IonButton,
  IonIcon,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonCardContent,
  IonSegment,
  IonSegmentButton,
  IonLabel,
  IonToast,
  IonSpinner,
  IonItem,
  IonSelect,
  IonSelectOption,
  IonBadge,
  IonChip,
} from '@ionic/vue';
import { syncOutline, chevronBackOutline } from 'ionicons/icons';
import statistiqueService from '@/services/statistique.service';
import anneeExerciceService from '@/services/annee-exercice.service';
import classeService from '@/services/classe.service';
import type {
  StatistiqueEnfant,
  StatistiqueStaff,
  StatistiqueFilterRequest,
  AnneeExercice,
  Classe,
} from '@/types';

// État
const activeTab = ref<'enfants' | 'staffs'>('enfants');
const loading = ref(false);
const error = ref<string | null>(null);

// Données
const statistiquesEnfants = ref<StatistiqueEnfant[]>([]);
const statistiquesStaffs = ref<StatistiqueStaff[]>([]);
const anneesExercice = ref<AnneeExercice[]>([]);
const classes = ref<Classe[]>([]);

// Filtres
const showFilters = ref(true);
const showFiltersStaff = ref(true);
const filterAnneeId = ref<number | null>(null);
const filterClasseId = ref<number | null>(null);
const filterGenre = ref<string | null>(null);
const filterStaffAnneeId = ref<number | null>(null);

// Watchers pour recharger les données quand les filtres changent
watch([filterAnneeId, filterClasseId, filterGenre], () => {
  if (activeTab.value === 'enfants') {
    loadStatistiquesEnfants();
  }
});

watch(filterStaffAnneeId, () => {
  if (activeTab.value === 'staffs') {
    loadStatistiquesStaffs();
  }
});

// Fonctions
const formatAnnee = (annee: string): string => {
  return annee.split('-')[0];
};

const formatPourcentage = (pourcentage: number): string => {
  return `${pourcentage.toFixed(2)}%`;
};

const getRangBadgeColor = (rang: number): string => {
  if (rang === 1) return 'warning'; // Or
  if (rang === 2) return 'medium';  // Argent
  if (rang === 3) return 'tertiary'; // Bronze
  return 'dark';
};

const onTabChange = (event: CustomEvent) => {
  activeTab.value = event.detail.value;
  if (activeTab.value === 'enfants') {
    loadStatistiquesEnfants();
  } else {
    loadStatistiquesStaffs();
  }
};

const resetFilters = () => {
  filterAnneeId.value = null;
  filterClasseId.value = null;
  filterGenre.value = null;
  loadStatistiquesEnfants();
};

const resetStaffFilters = () => {
  filterStaffAnneeId.value = null;
  loadStatistiquesStaffs();
};

const loadStatistiquesEnfants = async () => {
  try {
    loading.value = true;
    error.value = null;
    
    const filters: StatistiqueFilterRequest = {};
    if (filterAnneeId.value) filters.anneeExerciceId = filterAnneeId.value;
    if (filterClasseId.value) filters.classeId = filterClasseId.value;
    if (filterGenre.value) filters.genre = filterGenre.value;
    
    statistiquesEnfants.value = await statistiqueService.getStatistiquesEnfants(filters);
  } catch (err: any) {
    console.error('Erreur lors du chargement des statistiques enfants', err);
    error.value = err.response?.data?.message || 'Erreur lors du chargement des statistiques';
  } finally {
    loading.value = false;
  }
};

const loadStatistiquesStaffs = async () => {
  try {
    loading.value = true;
    error.value = null;
    
    const filters: StatistiqueFilterRequest = {};
    if (filterStaffAnneeId.value) filters.anneeExerciceId = filterStaffAnneeId.value;
    
    statistiquesStaffs.value = await statistiqueService.getStatistiquesStaffs(filters);
  } catch (err: any) {
    console.error('Erreur lors du chargement des statistiques staffs', err);
    error.value = err.response?.data?.message || 'Erreur lors du chargement des statistiques';
  } finally {
    loading.value = false;
  }
};

const loadAnneesExercice = async () => {
  try {
    anneesExercice.value = await anneeExerciceService.getAllAnneesExercice();
  } catch (err: any) {
    console.error('Erreur lors du chargement des années d\'exercice', err);
  }
};

const loadClasses = async () => {
  try {
    classes.value = await classeService.getAllClasses();
  } catch (err: any) {
    console.error('Erreur lors du chargement des classes', err);
  }
};

const loadData = async () => {
  await Promise.all([loadAnneesExercice(), loadClasses()]);
  if (activeTab.value === 'enfants') {
    await loadStatistiquesEnfants();
  } else {
    await loadStatistiquesStaffs();
  }
};

onMounted(() => {
  loadData();
});
</script>

<style scoped>
.header-logo {
  height: 32px;
  margin-left: 8px;
}

.stat-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 0;
  border-bottom: 1px solid var(--ion-color-light);
}

.stat-row:last-child {
  border-bottom: none;
}

.stat-value {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 4px;
}

.rotate-up {
  transform: rotate(-90deg);
  transition: transform 0.3s ease;
}

.rotate-down {
  transform: rotate(0deg);
  transition: transform 0.3s ease;
}

ion-card {
  margin: 12px;
}

ion-badge {
  font-size: 14px;
  padding: 6px 12px;
}

ion-chip {
  font-size: 12px;
  height: 24px;
}
</style>
