// mobile/src/views/CPDetailsPage.vue
<template>
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button default-href="/tabs/classes-progressives"></ion-back-button>
          <!-- <img src="/assets/logo.png" alt="Logo" class="header-logo" style="margin-left: 8px;" /> -->
        </ion-buttons>
        <ion-title v-if="cp">{{ formatDate(cp.dateCp) }}</ion-title>
        <ion-buttons slot="end">
          <ion-button @click="goToPresence">
            <ion-icon :icon="listOutline"></ion-icon>
          </ion-button>
          <ion-button v-if="canModify && cp?.etat !== 1" @click="openAddProgrammeModal">
            <ion-icon :icon="addOutline"></ion-icon>
          </ion-button>
        </ion-buttons>
      </ion-toolbar>
    </ion-header>

    <ion-content :fullscreen="true">
      <ion-refresher slot="fixed" @ionRefresh="handleRefresh($event)">
        <ion-refresher-content></ion-refresher-content>
      </ion-refresher>

      <!-- Info CP -->
      <div v-if="cp" class="ion-padding">
        <ion-card>
          <ion-card-header>
            <ion-card-title>{{ formatDate(cp.dateCp) }}</ion-card-title>
            <ion-card-subtitle>
              {{ cp.heureDebut }} - {{ cp.heureFin }}
              <span v-if="cp.niveau"> • {{ cp.niveau }}</span>
            </ion-card-subtitle>
          </ion-card-header>
          <ion-card-content>
            {{ cp.nombreProgrammes }} programme(s) planifié(s)
            <ion-badge v-if="cp.etat === 1" color="danger" style="margin-left: 8px;">
              🔒 Clôturée
            </ion-badge>
            <ion-badge v-else color="success" style="margin-left: 8px;">
              🔓 Ouverte
            </ion-badge>
          </ion-card-content>
        </ion-card>
        
        <!-- Message d'information si clôturée -->
        <ion-card v-if="cp.etat === 1" color="light">
          <ion-card-content>
            ℹ️ Cette CP est clôturée. Consultation uniquement - aucune modification autorisée.
          </ion-card-content>
        </ion-card>
      </div>

      <!-- Liste des programmes -->
      <ion-list v-if="!loading">
        <ion-list-header>
          <ion-label>Programmes planifiés</ion-label>
        </ion-list-header>

        <ion-item 
          v-for="detail in cpDetails" 
          :key="detail.id"
        >
          <ion-label>
            <h2>{{ detail.programmeNom || detail.description }}</h2>
            <p v-if="detail.programmeDescription" style="font-size: 0.85rem; color: var(--ion-color-medium);">
              {{ detail.programmeDescription }}
            </p>
            <p v-if="detail.classeNom" style="font-size: 0.85rem; color: var(--ion-color-medium);">
              🎯 {{ detail.classeNom }}
            </p>
            <p style="font-size: 0.85rem; color: var(--ion-color-medium-shade);">
              <ion-icon :icon="people"></ion-icon>
              <span v-if="detail.instructeurs.length > 0">
                {{ detail.instructeurs.map(i => i.prenom).join(', ') }}
              </span>
              <span v-else>Aucun instructeur assigné</span>
            </p>
            <p v-if="detail.statusNom" style="font-size: 0.8rem;">
              <ion-badge :color="getStatusColor(detail.statusNom)">
                {{ detail.statusNom }}
              </ion-badge>
            </p>
          </ion-label>
          <ion-buttons slot="end">
            <ion-button 
              v-if="canModify && cp?.etat !== 1"
              @click.stop="openEditInstructeursModal(detail)"
            >
              <ion-icon :icon="createOutline"></ion-icon>
            </ion-button>
            <ion-button 
              v-if="canModify && cp?.etat !== 1 && detail.statusNom && detail.statusNom !== 'Terminé'"
              color="primary"
              @click.stop="openChangeStatusModal(detail)"
            >
              <ion-icon :icon="checkmarkOutline"></ion-icon>
            </ion-button>
            <ion-button 
              v-if="canModify && cp?.etat !== 1 && detail.statusNom !== 'Terminé'"
              color="danger" 
              @click.stop="confirmDelete(detail.id)"
            >
              <ion-icon :icon="trashOutline"></ion-icon>
            </ion-button>
          </ion-buttons>
        </ion-item>

        <!-- Message si aucun programme -->
        <div v-if="cpDetails.length === 0" class="ion-padding ion-text-center">
          <ion-note>Aucun programme planifié pour cette CP</ion-note>
        </div>
      </ion-list>

      <!-- Skeleton lors du chargement -->
      <ion-list v-else>
        <ion-item v-for="i in 3" :key="i">
          <ion-label>
            <ion-skeleton-text animated style="width: 80%"></ion-skeleton-text>
            <ion-skeleton-text animated style="width: 60%"></ion-skeleton-text>
            <ion-skeleton-text animated style="width: 40%"></ion-skeleton-text>
          </ion-label>
        </ion-item>
      </ion-list>
    </ion-content>

    <!-- Modal sélection de programme avec filtres -->
    <ion-modal :is-open="showProgrammeModal">
      <ion-page>
        <ion-header>
          <ion-toolbar>
            <ion-title>Sélectionner un programme</ion-title>
            <ion-buttons slot="end">
              <ion-button @click="cancelProgrammeSelection">
                <ion-icon :icon="closeOutline"></ion-icon>
              </ion-button>
            </ion-buttons>
          </ion-toolbar>
        </ion-header>
        <ion-content>
          <div class="ion-padding">
            <!-- Filtres -->
            <ion-item>
              <ion-label>Catégorie</ion-label>
              <ion-select 
                v-model="selectedCategorieId" 
                placeholder="Toutes" 
                @ionChange="filterProgrammesList"
              >
                <ion-select-option :value="undefined">Toutes</ion-select-option>
                <ion-select-option 
                  v-for="cat in categories" 
                  :key="cat.id" 
                  :value="cat.id"
                >
                  {{ cat.nom }}
                </ion-select-option>
              </ion-select>
            </ion-item>

            <ion-item>
              <ion-label>Classe</ion-label>
              <ion-select 
                v-model="selectedClasseId" 
                placeholder="Toutes" 
                @ionChange="filterProgrammesList"
              >
                <ion-select-option :value="undefined">Toutes</ion-select-option>
                <ion-select-option 
                  v-for="classe in classes" 
                  :key="classe.id" 
                  :value="classe.id"
                >
                  {{ classe.nom }}
                </ion-select-option>
              </ion-select>
            </ion-item>

            <!-- Liste des programmes filtrés -->
            <ion-list>
              <ion-list-header>
                <ion-label>Programmes ({{ filteredProgrammes.length }})</ion-label>
              </ion-list-header>
              <ion-item 
                v-for="prog in filteredProgrammes" 
                :key="prog.id"
                button
                @click="selectProgrammeFromModal(prog)"
              >
                <ion-label>
                  <h2>{{ prog.nom }}</h2>
                  <p v-if="prog.description">{{ prog.description }}</p>
                  <p style="font-size: 0.85rem; color: var(--ion-color-medium);">
                    {{ prog.categorieNom }} • {{ prog.classeNom }}
                  </p>
                </ion-label>
              </ion-item>
              <div v-if="filteredProgrammes.length === 0" class="ion-padding ion-text-center">
                <ion-note>Aucun programme trouvé</ion-note>
              </div>
            </ion-list>
          </div>
        </ion-content>
      </ion-page>
    </ion-modal>

    <!-- Modal sélection instructeurs avec auto-complétion -->
    <ion-modal :is-open="showInstructeurModal">
      <ion-page>
        <ion-header>
          <ion-toolbar>
            <ion-title>Instructeurs</ion-title>
            <ion-buttons slot="end">
              <ion-button @click="cancelInstructeurSelection">
                <ion-icon :icon="closeOutline"></ion-icon>
              </ion-button>
            </ion-buttons>
          </ion-toolbar>
        </ion-header>
        <ion-content>
          <div class="ion-padding">
            <!-- Titre selon le contexte -->
            <h3 v-if="selectedProgramme">
              {{ selectedProgramme.nom }}
            </h3>
            <h3 v-else-if="isActiviteLibre">
              {{ activiteDescription }}
            </h3>

            <!-- Instructeurs déjà sélectionnés -->
            <div v-if="getSelectedInstructeursDetails().length > 0" class="ion-margin-bottom">
              <ion-label><strong>Instructeurs sélectionnés:</strong></ion-label>
              <div style="display: flex; flex-wrap: wrap; gap: 8px; margin-top: 8px;">
                <ion-chip 
                  v-for="inst in getSelectedInstructeursDetails()" 
                  :key="inst.id"
                  @click="removeInstructeur(inst.id)"
                >
                  <ion-label>{{ inst.prenom }} {{ inst.nom }}</ion-label>
                  <ion-icon :icon="closeOutline"></ion-icon>
                </ion-chip>
              </div>
            </div>

            <!-- Barre de recherche avec auto-complétion -->
            <ion-searchbar
              v-model="instructeurSearchText"
              placeholder="Rechercher un instructeur..."
              @ionInput="filterInstructeursList"
            ></ion-searchbar>

            <!-- Liste des instructeurs filtrés -->
            <ion-list>
              <ion-item 
                v-for="inst in filteredInstructeurs" 
                :key="inst.id"
                button
                @click="addInstructeurToSelection(inst)"
              >
                <ion-label>
                  <h3>{{ inst.prenom }} {{ inst.nom }}</h3>
                  <p v-if="inst.totem">{{ inst.totem }}</p>
                </ion-label>
              </ion-item>
              <div v-if="filteredInstructeurs.length === 0 && instructeurSearchText" class="ion-padding ion-text-center">
                <ion-note>Aucun instructeur trouvé</ion-note>
              </div>
            </ion-list>

            <!-- Bouton valider -->
            <div class="ion-padding-top">
              <ion-button 
                expand="block" 
                @click="confirmInstructeurSelection"
              >
                Valider{{ selectedInstructeurs.length > 0 ? ` (${selectedInstructeurs.length} instructeur${selectedInstructeurs.length > 1 ? 's' : ''})` : ' sans instructeur' }}
              </ion-button>
            </div>
          </div>
        </ion-content>
      </ion-page>
    </ion-modal>
  </ion-page>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonButtons,
  IonBackButton,
  IonButton,
  IonIcon,
  IonList,
  IonListHeader,
  IonItem,
  IonLabel,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonCardContent,
  IonBadge,
  IonRefresher,
  IonRefresherContent,
  IonSkeletonText,
  IonNote,
  IonModal,
  IonSearchbar,
  IonSelect,
  IonSelectOption,
  IonChip,
  actionSheetController,
  alertController,
  toastController
} from '@ionic/vue';
import { addOutline, createOutline, trashOutline, people, checkmarkOutline, closeOutline, listOutline } from 'ionicons/icons';
import { useAuthStore } from '@/stores/auth.store';
import classeProgressiveService from '@/services/classe-progressive.service';
import cpDetailsService from '@/services/cp-details.service';
import programmeService from '@/services/programme.service';
import instructeurService from '@/services/instructeur.service';
import programmeStatusService from '@/services/programme-status.service';
import categorieProgrammeService from '@/services/categorie-programme.service';
import classeService from '@/services/classe.service';
import type { ClasseProgressive, CpDetails, Programme, Instructeur, CategorieProgramme, Classe } from '@/types';

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const loading = ref(false);
const cp = ref<ClasseProgressive | null>(null);
const cpDetails = ref<CpDetails[]>([]);
const programmes = ref<Programme[]>([]);
const instructeurs = ref<Instructeur[]>([]);
const categories = ref<CategorieProgramme[]>([]);
const classes = ref<Classe[]>([]);

// États pour les modales
const showProgrammeModal = ref(false);
const showInstructeurModal = ref(false);
const selectedCategorieId = ref<number | undefined>();
const selectedClasseId = ref<number | undefined>();
const filteredProgrammes = ref<Programme[]>([]);
const selectedProgramme = ref<Programme | null>(null);
const isActiviteLibre = ref(false);
const activiteDescription = ref('');

// États pour auto-complétion instructeurs
const instructeurSearchText = ref('');
const selectedInstructeurs = ref<number[]>([]);
const filteredInstructeurs = ref<Instructeur[]>([]);

const canModify = computed(() => {
  const role = authStore.user?.role;
  return role === 'Directeur' || role === 'Co_Directeur';
});

onMounted(() => {
  loadData();
});

// Watchers
watch(instructeurSearchText, () => {
  filterInstructeursList();
});

async function loadData() {
  try {
    loading.value = true;
    const cpId = parseInt(route.params.id as string);
    await Promise.all([
      loadCP(cpId),
      loadCPDetails(cpId),
      loadProgrammes(),
      loadInstructeurs(),
      loadCategories(),
      loadClasses()
    ]);
  } finally {
    loading.value = false;
  }
}

async function loadCP(cpId: number) {
  try {
    cp.value = await classeProgressiveService.getCPById(cpId);
  } catch (error: any) {
    const toast = await toastController.create({
      message: error.message || 'Erreur lors du chargement de la CP',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}

async function loadCPDetails(cpId: number) {
  try {
    cpDetails.value = await cpDetailsService.getProgrammesByCP(cpId);
  } catch (error: any) {
    const toast = await toastController.create({
      message: error.message || 'Erreur lors du chargement des détails',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}

async function loadProgrammes() {
  try {
    programmes.value = await programmeService.getAllProgrammes();
  } catch (error: any) {
    console.error('Erreur chargement programmes:', error);
  }
}

async function loadInstructeurs() {
  try {
    instructeurs.value = await instructeurService.getAllInstructeurs();
  } catch (error: any) {
    console.error('Erreur chargement instructeurs:', error);
  }
}

async function loadCategories() {
  try {
    categories.value = await categorieProgrammeService.getAllCategories();
  } catch (error: any) {
    console.error('Erreur chargement catégories:', error);
  }
}

async function loadClasses() {
  try {
    classes.value = await classeService.getAllClasses();
  } catch (error: any) {
    console.error('Erreur chargement classes:', error);
  }
}

async function handleRefresh(event: any) {
  await loadData();
  event.target.complete();
}

function goToPresence() {
  const cpId = parseInt(route.params.id as string);
  router.push(`/tabs/cp-presence/${cpId}`);
}

function formatDate(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString('fr-FR', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
}

function getStatusColor(status: string): string {
  switch (status) {
    case 'En attente': return 'warning';
    case 'En cours': return 'primary';
    case 'Terminé': return 'success';
    default: return 'medium';
  }
}

async function openAddProgrammeModal() {
  const actionSheet = await actionSheetController.create({
    header: 'Ajouter à la CP',
    buttons: [
      {
        text: 'Programme',
        handler: () => openProgrammeSelectionModal()
      },
      {
        text: 'Activité libre',
        handler: () => showActiviteLibreForm()
      },
      {
        text: 'Annuler',
        role: 'cancel'
      }
    ]
  });
  await actionSheet.present();
}

function openProgrammeSelectionModal() {
  selectedCategorieId.value = undefined;
  selectedClasseId.value = undefined;
  filteredProgrammes.value = programmes.value;
  selectedProgramme.value = null;
  isActiviteLibre.value = false;
  showProgrammeModal.value = true;
}

async function filterProgrammesList() {
  try {
    if (selectedCategorieId.value || selectedClasseId.value) {
      filteredProgrammes.value = await programmeService.filterProgrammes(
        selectedCategorieId.value,
        selectedClasseId.value
      );
    } else {
      filteredProgrammes.value = programmes.value;
    }
  } catch (error: any) {
    console.error('Erreur filtrage programmes:', error);
    filteredProgrammes.value = programmes.value;
  }
}

function selectProgrammeFromModal(programme: Programme) {
  selectedProgramme.value = programme;
  isActiviteLibre.value = false;
  showProgrammeModal.value = false;
  openInstructeurSelectionModal();
}

function cancelProgrammeSelection() {
  showProgrammeModal.value = false;
  selectedCategorieId.value = undefined;
  selectedClasseId.value = undefined;
  selectedProgramme.value = null;
}

function closeProgrammeModal() {
  // Juste fermer sans reset - utilisé après sélection
  showProgrammeModal.value = false;
}

async function showActiviteLibreForm() {
  const alert = await alertController.create({
    header: 'Activité libre',
    inputs: [
      {
        name: 'description',
        type: 'textarea',
        placeholder: 'Description de l\'activité'
      }
    ],
    buttons: [
      {
        text: 'Annuler',
        role: 'cancel'
      },
      {
        text: 'Suivant',
        handler: (data) => {
          if (!data.description?.trim()) {
            return false;
          }
          activiteDescription.value = data.description;
          isActiviteLibre.value = true;
          selectedProgramme.value = null;
          openInstructeurSelectionModal();
          return true;
        }
      }
    ]
  });
  await alert.present();
}

function openInstructeurSelectionModal() {
  selectedInstructeurs.value = [];
  instructeurSearchText.value = '';
  filteredInstructeurs.value = instructeurs.value;
  showInstructeurModal.value = true;
}

function filterInstructeursList() {
  const searchLower = instructeurSearchText.value.toLowerCase();
  
  if (!searchLower) {
    // Exclure les instructeurs déjà sélectionnés
    filteredInstructeurs.value = instructeurs.value.filter(
      inst => !selectedInstructeurs.value.includes(inst.id)
    );
    return;
  }
  
  filteredInstructeurs.value = instructeurs.value.filter(inst => {
    // Exclure les déjà sélectionnés
    if (selectedInstructeurs.value.includes(inst.id)) return false;
    
    // Filtrer par recherche
    const fullName = `${inst.prenom} ${inst.nom} ${inst.totem || ''}`.toLowerCase();
    return fullName.includes(searchLower);
  });
}

function addInstructeurToSelection(instructeur: Instructeur) {
  if (!selectedInstructeurs.value.includes(instructeur.id)) {
    selectedInstructeurs.value.push(instructeur.id);
    instructeurSearchText.value = '';
    filterInstructeursList();
  }
}

function removeInstructeur(instructeurId: number) {
  selectedInstructeurs.value = selectedInstructeurs.value.filter(id => id !== instructeurId);
  filterInstructeursList();
}

function getSelectedInstructeursDetails() {
  return instructeurs.value.filter(inst => selectedInstructeurs.value.includes(inst.id));
}

async function confirmInstructeurSelection() {
  // Sauvegarder les valeurs AVANT de fermer
  const programmeToAdd = selectedProgramme.value;
  const descriptionToAdd = activiteDescription.value;
  const isActivite = isActiviteLibre.value;
  const instructeursToAdd = [...selectedInstructeurs.value];
  
  console.log('Confirmation - Instructeurs sélectionnés:', instructeursToAdd);
  console.log('Programme:', programmeToAdd);
  console.log('Activité libre:', isActivite, descriptionToAdd);
  
  // Fermer la modale
  closeInstructeurModal();
  
  // Réinitialiser les variables APRÈS la fermeture
  selectedInstructeurs.value = [];
  instructeurSearchText.value = '';
  isActiviteLibre.value = false;
  activiteDescription.value = '';
  selectedProgramme.value = null;
  selectedCategorieId.value = undefined;
  selectedClasseId.value = undefined;
  
  try {
    // Utiliser les valeurs sauvegardées
    if (isActivite) {
      await addProgrammeToCPWithInstructeurs(undefined, descriptionToAdd, instructeursToAdd);
    } else if (programmeToAdd) {
      await addProgrammeToCPWithInstructeurs(programmeToAdd.id, undefined, instructeursToAdd);
    } else {
      console.error('Aucun programme ni activité libre sélectionné');
      const toast = await toastController.create({
        message: 'Erreur: aucun programme sélectionné',
        duration: 3000,
        color: 'danger'
      });
      await toast.present();
    }
  } catch (error) {
    console.error('Erreur lors de la confirmation:', error);
  }
}

function cancelInstructeurSelection() {
  showInstructeurModal.value = false;
  selectedInstructeurs.value = [];
  instructeurSearchText.value = '';
  isActiviteLibre.value = false;
  activiteDescription.value = '';
  selectedProgramme.value = null;
}

function closeInstructeurModal() {
  // Juste fermer sans reset - utilisé après confirmation
  showInstructeurModal.value = false;
}

async function addProgrammeToCPWithInstructeurs(programmeId: number | undefined, description: string | undefined, instructeurIds: number[]) {
  try {
    const request = {
      classeProgressiveId: parseInt(route.params.id as string),
      programmeId,
      description,
      instructeurIds: instructeurIds
    };
    
    console.log('Envoi requête addProgrammeToCP:', request);
    
    const result = await cpDetailsService.addProgrammeToCP(request);
    console.log('Résultat addProgrammeToCP:', result);
    
    const toast = await toastController.create({
      message: 'Ajouté avec succès',
      duration: 2000,
      color: 'success'
    });
    await toast.present();
    await loadCPDetails(parseInt(route.params.id as string));
  } catch (error: any) {
    console.error('Erreur addProgrammeToCP:', error);
    const toast = await toastController.create({
      message: error.message || 'Erreur lors de l\'ajout',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}

async function openEditInstructeursModal(detail: CpDetails) {
  // Multi-select pour instructeurs - simplifiée pour mobile
  const currentIds = detail.instructeurs.map(i => i.id);
  selectedInstructeurs.value = [...currentIds];
  
  const alert = await alertController.create({
    header: 'Modifier instructeurs',
    message: 'Instructeurs actuels: ' + detail.instructeurs.map(i => i.prenom + ' ' + i.nom).join(', '),
    buttons: [
      {
        text: 'Réinitialiser',
        handler: () => {
          selectedInstructeurs.value = [];
          return false;
        }
      },
      {
        text: 'Valider',
        handler: async () => {
          await updateInstructeurs(detail.id);
        }
      },
      {
        text: 'Annuler',
        role: 'cancel'
      }
    ]
  });
  await alert.present();
}

async function updateInstructeurs(cpDetailsId: number) {
  try {
    await cpDetailsService.updateInstructeur(cpDetailsId, {
      instructeurIds: selectedInstructeurs.value
    });
    const toast = await toastController.create({
      message: 'Instructeurs modifiés',
      duration: 2000,
      color: 'success'
    });
    await toast.present();
    selectedInstructeurs.value = [];
    await loadCPDetails(parseInt(route.params.id as string));
  } catch (error: any) {
    const toast = await toastController.create({
      message: error.message || 'Erreur lors de la modification',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}

async function openChangeStatusModal(detail: CpDetails) {
  if (!detail.programmeId) return;
  
  const alert = await alertController.create({
    header: 'Marquer comme terminé',
    message: `Voulez-vous marquer "${detail.programmeNom || detail.description}" comme terminé ?`,
    buttons: [
      {
        text: 'Annuler',
        role: 'cancel'
      },
      {
        text: 'Confirmer',
        handler: () => changeStatusToTermine(detail.programmeId!)
      }
    ]
  });
  await alert.present();
}

async function changeStatusToTermine(programmeId: number) {
  try {
    const cpId = parseInt(route.params.id as string);
    // Statut ID 3 = Terminé
    await programmeStatusService.changeProgrammeStatus({
      programmeId,
      classeProgressiveId: cpId,
      newStatusId: 3
    });
    const toast = await toastController.create({
      message: 'Programme marqué comme terminé',
      duration: 2000,
      color: 'success'
    });
    await toast.present();
    await loadCPDetails(cpId);
  } catch (error: any) {
    const toast = await toastController.create({
      message: error.message || 'Erreur lors de la modification du statut',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}

async function confirmDelete(cpDetailsId: number) {
  const alert = await alertController.create({
    header: 'Confirmer la suppression',
    message: 'Voulez-vous vraiment retirer ce programme de la CP ?',
    buttons: [
      {
        text: 'Annuler',
        role: 'cancel'
      },
      {
        text: 'Supprimer',
        role: 'destructive',
        handler: () => deleteCPDetail(cpDetailsId)
      }
    ]
  });
  await alert.present();
}

async function deleteCPDetail(cpDetailsId: number) {
  try {
    await cpDetailsService.removeProgrammeFromCP(cpDetailsId);
    const toast = await toastController.create({
      message: 'Programme retiré de la CP',
      duration: 2000,
      color: 'success'
    });
    await toast.present();
    await loadCPDetails(parseInt(route.params.id as string));
  } catch (error: any) {
    const toast = await toastController.create({
      message: error.message || 'Erreur lors de la suppression',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}
</script>

<style scoped>
.header-logo {
  height: 32px;
  width: auto;
}
</style>

// frontend/src/pages/CPDetailsPage.tsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import cpDetailsService from '../services/cp-details.service';
import classeProgressiveService from '../services/classe-progressive.service';
import programmeService from '../services/programme.service';
import instructeurService from '../services/instructeur.service';
import categorieProgrammeService from '../services/categorie-programme.service';
import classeService from '../services/classe.service';
import programmeStatusService from '../services/programme-status.service';
import { CPPresenceModal } from '../components/CPPresenceModal';
import { useAuth } from '../contexts/AuthContext';
import type { 
  CpDetailsResponse, 
  AddProgrammeToCpRequest,
  UpdateCpDetailsInstructeurRequest,
  ClasseProgressive,
  Programme,
  InstructeurSuggestion,
  CategorieProgramme,
  Classe
} from '../types';
import './CPDetailsPage.css';

export function CPDetailsPage() {
  const { cpId } = useParams<{ cpId: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  
  const [cpDetails, setCpDetails] = useState<CpDetailsResponse[]>([]);
  const [cp, setCP] = useState<ClasseProgressive | null>(null);
  const [programmes, setProgrammes] = useState<Programme[]>([]);
  const [allProgrammes, setAllProgrammes] = useState<Programme[]>([]);
  const [categories, setCategories] = useState<CategorieProgramme[]>([]);
  const [classes, setClasses] = useState<Classe[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [showAddModal, setShowAddModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showPresenceModal, setShowPresenceModal] = useState(false);
  const [editingDetail, setEditingDetail] = useState<CpDetailsResponse | null>(null);
  
  // Filtres de programme
  const [selectedCategorieId, setSelectedCategorieId] = useState<number | ''>('');
  const [selectedClasseId, setSelectedClasseId] = useState<number | ''>('');
  
  // Auto-complétion instructeurs
  const [searchQuery, setSearchQuery] = useState('');
  const [suggestions, setSuggestions] = useState<InstructeurSuggestion[]>([]);
  const [selectedInstructeurs, setSelectedInstructeurs] = useState<InstructeurSuggestion[]>([]);
  const [editSelectedInstructeurs, setEditSelectedInstructeurs] = useState<InstructeurSuggestion[]>([]);

  const [addFormData, setAddFormData] = useState<AddProgrammeToCpRequest>({
    classeProgressiveId: Number(cpId),
    programmeId: undefined,
    description: '',
    instructeurIds: [],
  });

  const [activityType, setActivityType] = useState<'programme' | 'libre'>('programme');

  useEffect(() => {
    if (cpId) {
      loadData();
    }
  }, [cpId]);

  const loadData = async () => {
    try {
      setLoading(true);
      const [detailsData, cpData, progData, catData, classData] = await Promise.all([
        cpDetailsService.getCPDetails(Number(cpId)),
        classeProgressiveService.getCPById(Number(cpId)),
        programmeService.getAllProgrammes(),
        categorieProgrammeService.getAllCategories(),
        classeService.getAllClasses(),
      ]);
      setCpDetails(detailsData);
      setCP(cpData);
      setProgrammes(progData);
      setAllProgrammes(progData);
      setCategories(catData);
      setClasses(classData);
    } catch (err: any) {
      setError(err.message || 'Erreur lors du chargement des données');
    } finally {
      setLoading(false);
    }
  };
  
  // Filtrer les programmes selon la catégorie et classe sélectionnées
  useEffect(() => {
    let filtered = allProgrammes;
    
    if (selectedCategorieId) {
      filtered = filtered.filter(p => p.categorieId === selectedCategorieId);
    }
    
    if (selectedClasseId) {
      filtered = filtered.filter(p => p.classeId === selectedClasseId);
    }
    
    setProgrammes(filtered);
  }, [selectedCategorieId, selectedClasseId, allProgrammes]);

  const handleAddActivity = () => {
    setActivityType('programme');
    setSelectedCategorieId('');
    setSelectedClasseId('');
    setSearchQuery('');
    setSuggestions([]);
    setSelectedInstructeurs([]);
    setAddFormData({
      classeProgressiveId: Number(cpId),
      programmeId: undefined,
      description: '',
      instructeurIds: [],
    });
    setShowAddModal(true);
  };

  const handleActivityTypeChange = (type: 'programme' | 'libre') => {
    setActivityType(type);
    if (type === 'libre') {
      setAddFormData({
        ...addFormData,
        programmeId: undefined,
        description: '',
      });
    } else {
      setAddFormData({
        ...addFormData,
        programmeId: undefined,
        description: '',
      });
    }
  };
  
  // Gestion de l'auto-complétion pour les instructeurs (mode ajout)
  const handleSearchChange = async (value: string) => {
    setSearchQuery(value);
    
    if (value.trim().length >= 2) {
      try {
        const results = await instructeurService.searchInstructeurs(value);
        // Filtrer les instructeurs déjà sélectionnés
        const filtered = results.filter(
          r => !selectedInstructeurs.some(s => s.id === r.id)
        );
        setSuggestions(filtered);
      } catch (err) {
        console.error('Erreur de recherche:', err);
      }
    } else {
      setSuggestions([]);
    }
  };
  
  const handleSelectInstructeur = (instructeur: InstructeurSuggestion) => {
    setSelectedInstructeurs([...selectedInstructeurs, instructeur]);
    setSearchQuery('');
    setSuggestions([]);
  };
  
  const handleRemoveInstructeur = (instructeurId: number) => {
    setSelectedInstructeurs(selectedInstructeurs.filter(i => i.id !== instructeurId));
  };
  
  // Gestion de l'auto-complétion pour les instructeurs (mode édition)
  const handleEditSearchChange = async (value: string) => {
    setSearchQuery(value);
    
    if (value.trim().length >= 2) {
      try {
        const results = await instructeurService.searchInstructeurs(value);
        // Filtrer les instructeurs déjà sélectionnés
        const filtered = results.filter(
          r => !editSelectedInstructeurs.some(s => s.id === r.id)
        );
        setSuggestions(filtered);
      } catch (err) {
        console.error('Erreur de recherche:', err);
      }
    } else {
      setSuggestions([]);
    }
  };
  
  const handleEditSelectInstructeur = (instructeur: InstructeurSuggestion) => {
    setEditSelectedInstructeurs([...editSelectedInstructeurs, instructeur]);
    setSearchQuery('');
    setSuggestions([]);
  };
  
  const handleEditRemoveInstructeur = (instructeurId: number) => {
    setEditSelectedInstructeurs(editSelectedInstructeurs.filter(i => i.id !== instructeurId));
  };

  const handleSubmitAdd = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Vérifier si la CP est clôturée
    if (cp?.etat === 1) {
      setError('Impossible d\'ajouter une activité : la CP est clôturée');
      return;
    }
    
    if (activityType === 'programme' && !addFormData.programmeId) {
      setError('Veuillez sélectionner un programme');
      return;
    }

    if (activityType === 'libre' && !addFormData.description?.trim()) {
      setError('Veuillez entrer une description pour l\'activité libre');
      return;
    }

    if (selectedInstructeurs.length === 0) {
      setError('Veuillez sélectionner au moins un instructeur');
      return;
    }

    try {
      const dataToSend: AddProgrammeToCpRequest = {
        classeProgressiveId: Number(cpId),
        instructeurIds: selectedInstructeurs.map(i => i.id),
      };

      if (activityType === 'programme') {
        dataToSend.programmeId = addFormData.programmeId;
      } else {
        dataToSend.description = addFormData.description;
      }

      await cpDetailsService.addProgrammeToCP(dataToSend);
      setSuccess(`${activityType === 'programme' ? 'Programme' : 'Activité libre'} ajouté(e) avec succès !`);
      setShowAddModal(false);
      setError(null);
      setTimeout(() => setSuccess(null), 3000);
      loadData();
    } catch (err: any) {
      setError(err.response?.data?.message || 'Erreur lors de l\'ajout');
    }
  };

  const handleEditInstructeurs = (detail: CpDetailsResponse) => {
    setEditingDetail(detail);
    // Convertir les instructeurs du détail en InstructeurSuggestion
    const instructeursToEdit = detail.instructeurs.map(i => ({
      id: i.id,
      nomComplet: i.nomComplet,
      nom: '',
      prenom: ''
    }));
    setEditSelectedInstructeurs(instructeursToEdit);
    setSearchQuery('');
    setSuggestions([]);
    setShowEditModal(true);
  };

  const handleChangeStatus = async (detail: CpDetailsResponse, newStatusId: number, newStatusName: string) => {
    // Vérifier si la CP est clôturée
    if (cp?.etat === 1) {
      setError('Impossible de modifier le statut : la CP est clôturée');
      return;
    }

    // Vérifier si le programme est déjà terminé
    if (detail.statusNom === 'Terminé') {
      setError('Impossible de modifier le statut : le programme est déjà terminé');
      return;
    }

    if (!detail.programmeId) {
      setError('Impossible de changer le statut d\'une activité libre');
      return;
    }

    if (window.confirm(`Confirmer le passage au statut "${newStatusName}" ?`)) {
      try {
        await programmeStatusService.changeProgrammeStatus({
          programmeId: detail.programmeId,
          classeProgressiveId: Number(cpId),
          newStatusId
        });
        setSuccess(`Statut changé avec succès : ${newStatusName}`);
        setError(null);
        setTimeout(() => setSuccess(null), 3000);
        loadData();
      } catch (err: any) {
        setError(err.response?.data?.message || 'Erreur lors du changement de statut');
      }
    }
  };

  const handleSubmitEdit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Vérifier si la CP est clôturée
    if (cp?.etat === 1) {
      setError('Impossible de modifier les instructeurs : la CP est clôturée');
      return;
    }

    if (editSelectedInstructeurs.length === 0) {
      setError('Veuillez sélectionner au moins un instructeur');
      return;
    }

    try {
      const updateData: UpdateCpDetailsInstructeurRequest = {
        instructeurIds: editSelectedInstructeurs.map(i => i.id),
      };
      await cpDetailsService.updateInstructeurs(editingDetail!.id, updateData);
      setSuccess('Instructeurs mis à jour avec succès !');
      setShowEditModal(false);
      setError(null);
      setTimeout(() => setSuccess(null), 3000);
      loadData();
    } catch (err: any) {
      setError(err.response?.data?.message || 'Erreur lors de la mise à jour');
    }
  };

  const handleDelete = async (id: number) => {
    // Vérifier si la CP est clôturée
    if (cp?.etat === 1) {
      setError('Impossible de retirer cette activité : la CP est clôturée');
      return;
    }
    
    if (window.confirm('Êtes-vous sûr de vouloir retirer cette activité de la CP ?')) {
      try {
        await cpDetailsService.deleteCPDetail(id);
        setSuccess('Activité retirée avec succès !');
        setError(null);
        setTimeout(() => setSuccess(null), 3000);
        loadData();
      } catch (err: any) {
        setError(err.response?.data?.message || 'Erreur lors de la suppression');
      }
    }
  };

  if (loading && !cp) return <div className="loading">Chargement...</div>;

  return (
    <div className="cp-details-page">
      <div className="page-header">
        <div>
          <button className="btn btn-secondary" onClick={() => navigate('/cp')}>
            ← Retour aux CP
          </button>
          <h1>📋 Programmes et Activités de la CP</h1>
          {cp && (
            <>
              <p className="cp-info">
                {new Date(cp.dateCp).toLocaleDateString('fr-FR', {
                  weekday: 'long',
                  year: 'numeric',
                  month: 'long',
                  day: 'numeric'
                })} - {cp.heureDebut} à {cp.heureFin}
                {cp.niveau && <span className="badge badge-primary">{cp.niveau}</span>}
                {cp.etat === 1 && <span className="badge badge-danger" style={{ marginLeft: '8px' }}>🔒 Clôturée</span>}
              </p>
              {cp.etat === 1 && (
                <div className="alert alert-warning" style={{ marginTop: '8px' }}>
                  ⚠️ Cette CP est clôturée. Consultation uniquement - aucune modification autorisée.
                </div>
              )}
            </>
          )}
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button 
            className="btn btn-info" 
            onClick={() => setShowPresenceModal(true)}
            title={cp?.etat === 1 ? "Voir les participants de cette CP" : "Gérer la présence"}
          >
            👥 {cp?.etat === 1 ? 'Voir participants' : 'Gérer présence'}
          </button>
          <button 
            className="btn btn-primary" 
            onClick={handleAddActivity}
            disabled={cp?.etat === 1}
            title={cp?.etat === 1 ? "CP clôturée - ajout interdit" : "Ajouter une activité"}
          >
            + Ajouter une activité
          </button>
        </div>
      </div>

      {error && (
        <div className="alert alert-danger">
          {error}
          <button onClick={() => setError(null)}>×</button>
        </div>
      )}

      {success && (
        <div className="alert alert-success">
          {success}
          <button onClick={() => setSuccess(null)}>×</button>
        </div>
      )}

      <div className="activities-grid">
        {cpDetails.length === 0 ? (
          <div className="empty-state">
            <p>Aucune activité planifiée pour cette CP</p>
            <p className="text-muted">Cliquez sur "Ajouter une activité" pour commencer</p>
          </div>
        ) : (
          cpDetails.map(detail => (
            <div key={detail.id} className="activity-card">
              <div className="activity-header">
                <div>
                  {detail.programmeId ? (
                    <>
                      <h3>{detail.programmeName}</h3>
                      <div className="activity-meta">
                        <span className="badge badge-info">{detail.categorieName}</span>
                        {detail.statusNom && (
                          <span className={`badge badge-status badge-${detail.statusNom.toLowerCase().replace(' ', '-')}`}>
                            {detail.statusNom}
                          </span>
                        )}
                      </div>
                    </>
                  ) : (
                    <>
                      <h3>🎨 Activité libre</h3>
                      <p className="activity-description">{detail.description}</p>
                    </>
                  )}
                </div>
              </div>
              
              <div className="instructeurs-section">
                <h4>👥 Instructeurs ({detail.instructeurs.length})</h4>
                <div className="instructeurs-list">
                  {detail.instructeurs.map(instr => (
                    <span key={instr.id} className="instructeur-badge">
                      {instr.nomComplet}
                    </span>
                  ))}
                </div>
              </div>

              <div className="activity-actions">
                {/* Boutons de changement de statut (uniquement pour Directeur/Co-Directeur et programmes) */}
                {detail.programmeId && (user?.role === 'Directeur' || user?.role === 'Co_Directeur') && cp?.etat !== 1 && (
                  <>
                    {detail.statusNom === 'En attente' && (
                      <button
                        className="btn btn-sm btn-primary"
                        onClick={() => handleChangeStatus(detail, 2, 'En cours')}
                        title="Passer en cours"
                      >
                        ▶️ En cours
                      </button>
                    )}
                    {detail.statusNom === 'En cours' && (
                      <button
                        className="btn btn-sm btn-success"
                        onClick={() => handleChangeStatus(detail, 3, 'Terminé')}
                        title="Marquer comme terminé"
                      >
                        ✅ Terminé
                      </button>
                    )}
                  </>
                )}
                
                <button
                  className="btn btn-sm btn-info"
                  onClick={() => handleEditInstructeurs(detail)}
                  disabled={cp?.etat === 1}
                  title={cp?.etat === 1 ? "CP clôturée - modification interdite" : "Modifier les instructeurs"}
                >
                  ✏️ Instructeurs
                </button>
                <button
                  className="btn btn-sm btn-danger"
                  onClick={() => handleDelete(detail.id)}
                  disabled={detail.statusNom === 'Terminé' || cp?.etat === 1}
                  title={cp?.etat === 1 ? "CP clôturée - suppression interdite" : detail.statusNom === 'Terminé' ? "Programme terminé" : "Retirer de la CP"}
                >
                  🗑️ Retirer
                </button>
              </div>
            </div>
          ))
        )}
      </div>

      {/* Modal Ajout */}
      {showAddModal && (
        <div className="modal-overlay" onClick={() => setShowAddModal(false)}>
          <div className="modal-content modal-large" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Ajouter une activité à la CP</h2>
              <button className="close-btn" onClick={() => setShowAddModal(false)}>×</button>
            </div>
            <form onSubmit={handleSubmitAdd}>
              <div className="activity-type-selector">
                <label>
                  <input
                    type="radio"
                    name="activityType"
                    value="programme"
                    checked={activityType === 'programme'}
                    onChange={() => handleActivityTypeChange('programme')}
                  />
                  <span>📖 Programme officiel</span>
                </label>
                <label>
                  <input
                    type="radio"
                    name="activityType"
                    value="libre"
                    checked={activityType === 'libre'}
                    onChange={() => handleActivityTypeChange('libre')}
                  />
                  <span>🎨 Activité libre</span>
                </label>
              </div>

              {activityType === 'programme' ? (
                <>
                  <div className="form-row">
                    <div className="form-group">
                      <label htmlFor="categorieFilter">Catégorie</label>
                      <select
                        id="categorieFilter"
                        className="form-control"
                        value={selectedCategorieId}
                        onChange={(e) => setSelectedCategorieId(e.target.value ? Number(e.target.value) : '')}
                      >
                        <option value="">Toutes les catégories</option>
                        {categories.map(cat => (
                          <option key={cat.id} value={cat.id}>
                            {cat.nom}
                          </option>
                        ))}
                      </select>
                    </div>
                    <div className="form-group">
                      <label htmlFor="classeFilter">Classe</label>
                      <select
                        id="classeFilter"
                        className="form-control"
                        value={selectedClasseId}
                        onChange={(e) => setSelectedClasseId(e.target.value ? Number(e.target.value) : '')}
                      >
                        <option value="">Toutes les classes</option>
                        {classes.map(cls => (
                          <option key={cls.id} value={cls.id}>
                            {cls.nom}
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>
                  <div className="form-group">
                    <label htmlFor="programmeId">Programme *</label>
                    <select
                      id="programmeId"
                      className="form-control"
                      value={addFormData.programmeId || ''}
                      onChange={(e) => setAddFormData({ ...addFormData, programmeId: Number(e.target.value) })}
                      required
                    >
                      <option value="">Sélectionner un programme</option>
                      {programmes.map(prog => (
                        <option key={prog.id} value={prog.id}>
                          {prog.nom} - {prog.categorieNom} ({prog.classeNom})
                        </option>
                      ))}
                    </select>
                    {programmes.length === 0 && (
                      <small className="text-muted">
                        Aucun programme trouvé avec ces filtres
                      </small>
                    )}
                  </div>
                </>
              ) : (
                <div className="form-group">
                  <label htmlFor="description">Description de l'activité *</label>
                  <textarea
                    id="description"
                    className="form-control"
                    rows={3}
                    value={addFormData.description}
                    onChange={(e) => setAddFormData({ ...addFormData, description: e.target.value })}
                    placeholder="Ex: Atelier de bricolage pour la fête des pères"
                    required={activityType === 'libre'}
                  />
                </div>
              )}

              <div className="form-group">
                <label>Instructeurs * (au moins 1)</label>
                
                {/* Auto-complétion */}
                <div className="autocomplete-container">
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Rechercher un instructeur..."
                    value={searchQuery}
                    onChange={(e) => handleSearchChange(e.target.value)}
                    autoComplete="off"
                  />
                  {suggestions.length > 0 && (
                    <ul className="suggestions-list">
                      {suggestions.map(instr => (
                        <li
                          key={instr.id}
                          onClick={() => handleSelectInstructeur(instr)}
                          className="suggestion-item"
                        >
                          {instr.nomComplet}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
                
                {/* Liste des instructeurs sélectionnés */}
                {selectedInstructeurs.length > 0 && (
                  <div className="selected-instructeurs">
                    <label className="text-muted">Instructeurs sélectionnés:</label>
                    <div className="instructeurs-chips">
                      {selectedInstructeurs.map(instr => (
                        <span key={instr.id} className="instructeur-chip">
                          {instr.nomComplet}
                          <button
                            type="button"
                            onClick={() => handleRemoveInstructeur(instr.id)}
                            className="chip-remove"
                            title="Retirer"
                          >
                            ×
                          </button>
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setShowAddModal(false)}>
                  Annuler
                </button>
                <button type="submit" className="btn btn-primary">
                  Ajouter
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Modal Modification */}
      {showEditModal && editingDetail && (
        <div className="modal-overlay" onClick={() => setShowEditModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Modifier les instructeurs</h2>
              <button className="close-btn" onClick={() => setShowEditModal(false)}>×</button>
            </div>
            <form onSubmit={handleSubmitEdit}>
              <div className="form-group">
                <label>
                  {editingDetail.programmeId ? editingDetail.programmeName : editingDetail.description}
                </label>
                
                {/* Auto-complétion */}
                <div className="autocomplete-container">
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Rechercher un instructeur..."
                    value={searchQuery}
                    onChange={(e) => handleEditSearchChange(e.target.value)}
                    autoComplete="off"
                  />
                  {suggestions.length > 0 && (
                    <ul className="suggestions-list">
                      {suggestions.map(instr => (
                        <li
                          key={instr.id}
                          onClick={() => handleEditSelectInstructeur(instr)}
                          className="suggestion-item"
                        >
                          {instr.nomComplet}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
                
                {/* Liste des instructeurs sélectionnés */}
                {editSelectedInstructeurs.length > 0 && (
                  <div className="selected-instructeurs">
                    <label className="text-muted">Instructeurs sélectionnés:</label>
                    <div className="instructeurs-chips">
                      {editSelectedInstructeurs.map(instr => (
                        <span key={instr.id} className="instructeur-chip">
                          {instr.nomComplet}
                          <button
                            type="button"
                            onClick={() => handleEditRemoveInstructeur(instr.id)}
                            className="chip-remove"
                            title="Retirer"
                          >
                            ×
                          </button>
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setShowEditModal(false)}>
                  Annuler
                </button>
                <button type="submit" className="btn btn-primary">
                  Enregistrer
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Modal de gestion de présence */}
      {showPresenceModal && cp && (
        <CPPresenceModal
          classeProgressiveId={Number(cpId)}
          cpDate={cp.dateCp}
          cpEtat={cp.etat}
          onClose={() => setShowPresenceModal(false)}
          onSuccess={() => {
            setSuccess('Présence enregistrée avec succès');
            setTimeout(() => setSuccess(null), 3000);
          }}
        />
      )}
    </div>
  );
}
