// mobile/src/views/ProgrammesPage.vue
<template>
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button default-href="/tabs/home"></ion-back-button>
          <!-- <img src="/assets/logo.png" alt="Logo" class="header-logo" style="margin-left: 8px;" /> -->
        </ion-buttons>
        <ion-title>Programmes</ion-title>
        <ion-buttons slot="end">
          <ion-button @click="showFilters = !showFilters">
            <ion-icon :icon="filterOutline"></ion-icon>
          </ion-button>
          <ion-button v-if="canModify" @click="openCreateModal">
            <ion-icon :icon="addOutline"></ion-icon>
          </ion-button>
        </ion-buttons>
      </ion-toolbar>
    </ion-header>

    <ion-content :fullscreen="true">
      <ion-refresher slot="fixed" @ionRefresh="handleRefresh($event)">
        <ion-refresher-content></ion-refresher-content>
      </ion-refresher>

      <!-- Filtres -->
      <div v-if="showFilters" class="ion-padding-horizontal ion-margin-top">
        <ion-item>
          <ion-label>Catégorie</ion-label>
          <ion-select v-model="filterCategorieId" interface="action-sheet" placeholder="Toutes">
            <ion-select-option :value="null">Toutes les catégories</ion-select-option>
            <ion-select-option 
              v-for="categorie in categories" 
              :key="categorie.id" 
              :value="categorie.id"
            >
              {{ categorie.nom }}
            </ion-select-option>
          </ion-select>
        </ion-item>

        <ion-item>
          <ion-label>Classe</ion-label>
          <ion-select v-model="filterClasseId" interface="action-sheet" placeholder="Toutes">
            <ion-select-option :value="null">Toutes les classes</ion-select-option>
            <ion-select-option 
              v-for="classe in classes" 
              :key="classe.id" 
              :value="classe.id"
            >
              {{ classe.nom }}
            </ion-select-option>
          </ion-select>
        </ion-item>

        <p v-if="filterCategorieId || filterClasseId" class="ion-padding-start ion-text-sm">
          {{ filteredProgrammes.length }} programme(s)
        </p>
      </div>

      <!-- Liste des programmes -->
      <ion-list v-if="!loading">
        <ion-item 
          v-for="programme in filteredProgrammes" 
          :key="programme.id"
        >
          <ion-label>
            <h2>{{ programme.nom }}</h2>
            <p class="ion-text-wrap" style="font-size: 0.85rem; color: var(--ion-color-medium);">
              {{ programme.categorieNom }} • {{ programme.classeNom }}
            </p>
            <p v-if="programme.description" class="ion-text-wrap" style="font-size: 0.8rem; color: var(--ion-color-medium-shade);">
              {{ programme.description }}
            </p>
          </ion-label>
          <ion-buttons slot="end">
            <ion-button 
              v-if="canModify"
              @click.stop="openEditModal(programme)"
            >
              <ion-icon :icon="createOutline"></ion-icon>
            </ion-button>
            <ion-button 
              v-if="canModify"
              color="danger" 
              @click.stop="confirmDelete(programme.id)"
            >
              <ion-icon :icon="trashOutline"></ion-icon>
            </ion-button>
          </ion-buttons>
        </ion-item>

        <!-- Message si aucun programme -->
        <div v-if="filteredProgrammes.length === 0" class="ion-padding ion-text-center">
          <ion-note>Aucun programme trouvé</ion-note>
        </div>
      </ion-list>

      <!-- Skeleton lors du chargement -->
      <ion-list v-else>
        <ion-item v-for="i in 5" :key="i">
          <ion-label>
            <ion-skeleton-text animated style="width: 80%"></ion-skeleton-text>
            <ion-skeleton-text animated style="width: 60%"></ion-skeleton-text>
            <ion-skeleton-text animated style="width: 40%"></ion-skeleton-text>
          </ion-label>
        </ion-item>
      </ion-list>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonButtons,
  IonBackButton,
  IonButton,
  IonIcon,
  IonList,
  IonItem,
  IonLabel,
  IonRefresher,
  IonRefresherContent,
  IonSelect,
  IonSelectOption,
  IonSkeletonText,
  IonNote,
  alertController,
  modalController,
  toastController
} from '@ionic/vue';
import { addOutline, createOutline, trashOutline, filterOutline } from 'ionicons/icons';
import { useAuthStore } from '@/stores/auth.store';
import programmeService from '@/services/programme.service';
import categorieProgrammeService from '@/services/categorie-programme.service';
import classeService from '@/services/classe.service';
import type { Programme, CategorieProgramme, Classe } from '@/types';

const authStore = useAuthStore();
const loading = ref(false);
const programmes = ref<Programme[]>([]);
const categories = ref<CategorieProgramme[]>([]);
const classes = ref<Classe[]>([]);
const showFilters = ref(false);
const filterCategorieId = ref<number | null>(null);
const filterClasseId = ref<number | null>(null);

const canModify = computed(() => {
  const role = authStore.user?.role;
  return role === 'Directeur' || role === 'Co_Directeur';
});

const filteredProgrammes = computed(() => {
  let result = programmes.value;
  
  if (filterCategorieId.value) {
    result = result.filter(p => p.categorieId === filterCategorieId.value);
  }
  
  if (filterClasseId.value) {
    result = result.filter(p => p.classeId === filterClasseId.value);
  }
  
  return result;
});

onMounted(() => {
  loadData();
});

async function loadData() {
  try {
    loading.value = true;
    await Promise.all([
      loadProgrammes(),
      loadCategories(),
      loadClasses()
    ]);
  } finally {
    loading.value = false;
  }
}

async function loadProgrammes() {
  try {
    programmes.value = await programmeService.getAllProgrammes();
  } catch (error: any) {
    const toast = await toastController.create({
      message: error.message || 'Erreur lors du chargement des programmes',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}

async function loadCategories() {
  try {
    categories.value = await categorieProgrammeService.getAllCategories();
  } catch (error: any) {
    console.error('Erreur chargement catégories:', error);
  }
}

async function loadClasses() {
  try {
    classes.value = await classeService.getAllClasses();
  } catch (error: any) {
    console.error('Erreur chargement classes:', error);
  }
}

async function handleRefresh(event: any) {
  await loadData();
  event.target.complete();
}

async function openCreateModal() {
  const alert = await alertController.create({
    header: 'Nouveau Programme',
    inputs: [
      {
        name: 'nom',
        type: 'text',
        placeholder: 'Nom du programme'
      },
      {
        name: 'description',
        type: 'textarea',
        placeholder: 'Description (optionnel)'
      }
    ],
    buttons: [
      {
        text: 'Annuler',
        role: 'cancel'
      },
      {
        text: 'Suivant',
        handler: async (data) => {
          if (!data.nom?.trim()) {
            const toast = await toastController.create({
              message: 'Le nom est requis',
              duration: 2000,
              color: 'warning'
            });
            await toast.present();
            return false;
          }
          await showCategoryAndClassSelection(data.nom, data.description);
          return true;
        }
      }
    ]
  });
  await alert.present();
}

async function showCategoryAndClassSelection(nom: string, description: string) {
  const alert = await alertController.create({
    header: 'Sélectionner Catégorie et Classe',
    inputs: [
      {
        label: 'Catégorie',
        type: 'radio',
        value: categories.value[0]?.id,
        checked: true
      },
      ...categories.value.map(cat => ({
        label: cat.nom,
        type: 'radio' as const,
        value: cat.id
      }))
    ],
    buttons: [
      {
        text: 'Retour',
        role: 'cancel'
      },
      {
        text: 'Suivant',
        handler: async (categorieId) => {
          await showClassSelection(nom, description, categorieId);
        }
      }
    ]
  });
  await alert.present();
}

async function showClassSelection(nom: string, description: string, categorieId: number) {
  const alert = await alertController.create({
    header: 'Sélectionner une Classe',
    inputs: classes.value.map((classe, index) => ({
      label: classe.nom,
      type: 'radio' as const,
      value: classe.id,
      checked: index === 0
    })),
    buttons: [
      {
        text: 'Retour',
        role: 'cancel'
      },
      {
        text: 'Créer',
        handler: async (classeId) => {
          await createProgramme(nom, description, categorieId, classeId);
        }
      }
    ]
  });
  await alert.present();
}

async function createProgramme(nom: string, description: string, categorieId: number, classeId: number) {
  try {
    await programmeService.createProgramme({ nom, description, categorieId, classeId });
    const toast = await toastController.create({
      message: 'Programme créé avec succès',
      duration: 2000,
      color: 'success'
    });
    await toast.present();
    await loadProgrammes();
  } catch (error: any) {
    const toast = await toastController.create({
      message: error.message || 'Erreur lors de la création',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}

async function openEditModal(programme: Programme) {
  const alert = await alertController.create({
    header: 'Modifier Programme',
    inputs: [
      {
        name: 'nom',
        type: 'text',
        value: programme.nom,
        placeholder: 'Nom du programme'
      },
      {
        name: 'description',
        type: 'textarea',
        value: programme.description,
        placeholder: 'Description (optionnel)'
      }
    ],
    buttons: [
      {
        text: 'Annuler',
        role: 'cancel'
      },
      {
        text: 'Modifier',
        handler: async (data) => {
          if (!data.nom?.trim()) {
            const toast = await toastController.create({
              message: 'Le nom est requis',
              duration: 2000,
              color: 'warning'
            });
            await toast.present();
            return false;
          }
          await updateProgramme(programme.id, data.nom, data.description, programme.categorieId, programme.classeId);
          return true;
        }
      }
    ]
  });
  await alert.present();
}

async function updateProgramme(id: number, nom: string, description: string, categorieId: number, classeId: number) {
  try {
    await programmeService.updateProgramme(id, { nom, description, categorieId, classeId });
    const toast = await toastController.create({
      message: 'Programme modifié avec succès',
      duration: 2000,
      color: 'success'
    });
    await toast.present();
    await loadProgrammes();
  } catch (error: any) {
    const toast = await toastController.create({
      message: error.message || 'Erreur lors de la modification',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}

async function confirmDelete(id: number) {
  const alert = await alertController.create({
    header: 'Confirmer la suppression',
    message: 'Voulez-vous vraiment supprimer ce programme ?',
    buttons: [
      {
        text: 'Annuler',
        role: 'cancel'
      },
      {
        text: 'Supprimer',
        role: 'destructive',
        handler: () => deleteProgramme(id)
      }
    ]
  });
  await alert.present();
}

async function deleteProgramme(id: number) {
  try {
    await programmeService.deleteProgramme(id);
    const toast = await toastController.create({
      message: 'Programme supprimé avec succès',
      duration: 2000,
      color: 'success'
    });
    await toast.present();
    await loadProgrammes();
  } catch (error: any) {
    const toast = await toastController.create({
      message: error.message || 'Erreur lors de la suppression',
      duration: 3000,
      color: 'danger'
    });
    await toast.present();
  }
}
</script>

<style scoped>
.header-logo {
  height: 32px;
  width: auto;
}
</style>

// frontend/src/pages/ProgrammesPage.tsx
import { useState, useEffect } from 'react';
import programmeService from '../services/programme.service';
import categorieProgrammeService from '../services/categorie-programme.service';
import classeService from '../services/classe.service';
import type { 
  Programme, 
  CreateProgrammeRequest,
  CategorieProgramme,
  Classe
} from '../types';
import './ProgrammesPage.css';

export function ProgrammesPage() {
  const [programmes, setProgrammes] = useState<Programme[]>([]);
  const [categories, setCategories] = useState<CategorieProgramme[]>([]);
  const [classes, setClasses] = useState<Classe[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [showModal, setShowModal] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  
  // Filtres
  const [filters, setFilters] = useState({
    categorieId: '',
    classeId: '',
    nom: '',
  });

  const [formData, setFormData] = useState<CreateProgrammeRequest>({
    nom: '',
    description: '',
    categorieId: 0,
    classeId: 0,
  });

  useEffect(() => {
    loadInitialData();
  }, []);

  const loadInitialData = async () => {
    try {
      setLoading(true);
      const [progData, catData, classeData] = await Promise.all([
        programmeService.getAllProgrammes(),
        categorieProgrammeService.getAllCategories(),
        classeService.getAllClasses(),
      ]);
      setProgrammes(progData);
      setCategories(catData);
      setClasses(classeData);
    } catch (err: any) {
      setError(err.message || 'Erreur lors du chargement des données');
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = async () => {
    try {
      setLoading(true);
      const params: any = {};
      if (filters.categorieId) params.categorieId = Number(filters.categorieId);
      if (filters.classeId) params.classeId = Number(filters.classeId);
      if (filters.nom) params.nom = filters.nom;

      const data = await programmeService.searchProgrammes(params);
      setProgrammes(data);
    } catch (err: any) {
      setError(err.message || 'Erreur lors de la recherche');
    } finally {
      setLoading(false);
    }
  };

  const handleResetFilters = async () => {
    setFilters({ categorieId: '', classeId: '', nom: '' });
    try {
      setLoading(true);
      const data = await programmeService.getAllProgrammes();
      setProgrammes(data);
    } catch (err: any) {
      setError(err.message || 'Erreur lors du chargement');
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = () => {
    setEditingId(null);
    setFormData({
      nom: '',
      description: '',
      categorieId: categories.length > 0 ? categories[0].id : 0,
      classeId: classes.length > 0 ? classes[0].id : 0,
    });
    setShowModal(true);
  };

  const handleEdit = (programme: Programme) => {
    setEditingId(programme.id);
    setFormData({
      nom: programme.nom,
      description: programme.description || '',
      categorieId: programme.categorieId,
      classeId: programme.classeId,
    });
    setShowModal(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (editingId) {
        await programmeService.updateProgramme(editingId, formData);
        setSuccess('Programme modifié avec succès !');
      } else {
        await programmeService.createProgramme(formData);
        setSuccess('Programme créé avec succès !');
      }
      setShowModal(false);
      setError(null);
      setTimeout(() => setSuccess(null), 3000);
      handleResetFilters();
    } catch (err: any) {
      setError(err.response?.data?.message || 'Erreur lors de l\'enregistrement');
    }
  };

  const handleDelete = async (id: number) => {
    if (window.confirm('Êtes-vous sûr de vouloir supprimer ce programme ?')) {
      try {
        await programmeService.deleteProgramme(id);
        setSuccess('Programme supprimé avec succès !');
        setError(null);
        setTimeout(() => setSuccess(null), 3000);
        handleResetFilters();
      } catch (err: any) {
        setError(err.response?.data?.message || 'Erreur lors de la suppression');
      }
    }
  };

  if (loading && programmes.length === 0) return <div className="loading">Chargement...</div>;

  return (
    <div className="programmes-page">
      <div className="page-header">
        <h1>📖 Gestion des Programmes</h1>
        <button className="btn btn-primary" onClick={handleCreate}>
          + Nouveau Programme
        </button>
      </div>

      {error && (
        <div className="alert alert-danger">
          {error}
          <button onClick={() => setError(null)}>×</button>
        </div>
      )}

      {success && (
        <div className="alert alert-success">
          {success}
          <button onClick={() => setSuccess(null)}>×</button>
        </div>
      )}

      {/* Filtres */}
      <div className="filters-card">
        <h3>🔍 Filtres de recherche</h3>
        <div className="filters-grid">
          <div className="form-group">
            <label>Catégorie</label>
            <select
              className="form-control"
              value={filters.categorieId}
              onChange={(e) => setFilters({ ...filters, categorieId: e.target.value })}
            >
              <option value="">Toutes les catégories</option>
              {categories.map(cat => (
                <option key={cat.id} value={cat.id}>{cat.nom}</option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <label>Classe</label>
            <select
              className="form-control"
              value={filters.classeId}
              onChange={(e) => setFilters({ ...filters, classeId: e.target.value })}
            >
              <option value="">Toutes les classes</option>
              {classes.map(classe => (
                <option key={classe.id} value={classe.id}>{classe.nom}</option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <label>Nom du programme</label>
            <input
              type="text"
              className="form-control"
              value={filters.nom}
              onChange={(e) => setFilters({ ...filters, nom: e.target.value })}
              placeholder="Rechercher..."
            />
          </div>
          <div className="form-group filter-actions">
            <button className="btn btn-primary" onClick={handleSearch}>
              Rechercher
            </button>
            <button className="btn btn-secondary" onClick={handleResetFilters}>
              Réinitialiser
            </button>
          </div>
        </div>
      </div>

      <div className="table-container">
        <table className="data-table">
          <thead>
            <tr>
              <th>Nom</th>
              <th>Description</th>
              <th>Catégorie</th>
              <th>Classe</th>
              <th>Date de création</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {programmes.length === 0 ? (
              <tr>
                <td colSpan={6} className="text-center">Aucun programme trouvé</td>
              </tr>
            ) : (
              programmes.map(programme => (
                <tr key={programme.id}>
                  <td><strong>{programme.nom}</strong></td>
                  <td>{programme.description || '-'}</td>
                  <td>
                    <span className="badge badge-info">{programme.categorieNom}</span>
                  </td>
                  <td>
                    <span className="badge badge-primary">{programme.classeNom}</span>
                  </td>
                  <td>{new Date(programme.createdAt).toLocaleDateString('fr-FR')}</td>
                  <td className="actions">
                    <button
                      className="btn btn-sm btn-info"
                      onClick={() => handleEdit(programme)}
                      title="Modifier"
                    >
                      ✏️
                    </button>
                    <button
                      className="btn btn-sm btn-danger"
                      onClick={() => handleDelete(programme.id)}
                      title="Supprimer"
                    >
                      🗑️
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Modal */}
      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>{editingId ? 'Modifier le programme' : 'Nouveau programme'}</h2>
              <button className="close-btn" onClick={() => setShowModal(false)}>×</button>
            </div>
            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label htmlFor="nom">Nom *</label>
                <input
                  id="nom"
                  type="text"
                  className="form-control"
                  value={formData.nom}
                  onChange={(e) => setFormData({ ...formData, nom: e.target.value })}
                  required
                />
              </div>
              <div className="form-group">
                <label htmlFor="description">Description</label>
                <textarea
                  id="description"
                  className="form-control"
                  rows={3}
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label htmlFor="categorieId">Catégorie *</label>
                <select
                  id="categorieId"
                  className="form-control"
                  value={formData.categorieId}
                  onChange={(e) => setFormData({ ...formData, categorieId: Number(e.target.value) })}
                  required
                >
                  <option value="">Sélectionner une catégorie</option>
                  {categories.map(cat => (
                    <option key={cat.id} value={cat.id}>{cat.nom}</option>
                  ))}
                </select>
              </div>
              <div className="form-group">
                <label htmlFor="classeId">Classe *</label>
                <select
                  id="classeId"
                  className="form-control"
                  value={formData.classeId}
                  onChange={(e) => setFormData({ ...formData, classeId: Number(e.target.value) })}
                  required
                >
                  <option value="">Sélectionner une classe</option>
                  {classes.map(classe => (
                    <option key={classe.id} value={classe.id}>{classe.nom}</option>
                  ))}
                </select>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setShowModal(false)}>
                  Annuler
                </button>
                <button type="submit" className="btn btn-primary">
                  {editingId ? 'Modifier' : 'Créer'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
